
deploy_staging_iot_agent:
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-builders/gitlab_agent_deploy:v2752318-c3e56c1
  tags: [ "runner:main", "size:large" ]
  dependencies: []
  script:
    - wget http://s3.amazonaws.com/dsd6-staging/linux/dogstatsd-
    - wget http://s3.amazonaws.com/dsd6-staging/linux/iot/agent-
    - aws s3 cp --only-show-errors --region us-east-1 --sse AES256 ./dogstatsd- s3://dsd6-staging/linux/dogstatsd-7.21.1 --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers full=id=3a6e02b08553fd157ae3fb918945dd1eaae5a1aa818940381ef07a430cf25732
    - aws s3 cp --only-show-errors --region us-east-1 --sse AES256 ./agent- s3://dsd6-staging/linux/iot/agent-7.21.1 --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers full=id=3a6e02b08553fd157ae3fb918945dd1eaae5a1aa818940381ef07a430cf25732

