default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure

variables:
  DATADOG_AGENT_BUILDIMAGES: v2424505-0439a40

stages:
  - test_job
  - on_success_or_failure
  - trigger_release


test-job:
  stage: test_job
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64:$DATADOG_AGENT_BUILDIMAGES
  tags: [ "runner:main", "size:2xlarge" ]
  script:
    - (( $RANDOM >> 14 )) && exit 0 || exit 1

on-success-job:
  stage: on_success_or_failure
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64:$DATADOG_AGENT_BUILDIMAGES
  tags: [ "runner:main", "size:2xlarge" ]
  script:
    - echo "Success"
  when: on_success

on-failure-job:
  stage: on_success_or_failure
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64:$DATADOG_AGENT_BUILDIMAGES
  tags: [ "runner:main", "size:2xlarge" ]
  script:
    - echo "Failure"
  when: on_failure

#
# Trigger release pipelines
#
trigger_release_7:
  stage: trigger_release
  variables:
    RELEASE_VERSION: "nightly-a7"
  trigger:
    project: DataDog/agent-release-management
    branch: master
  when: manual

trigger_release_6:
  stage: trigger_release
  variables:
    RELEASE_VERSION: "nightly"
  trigger:
    project: DataDog/agent-release-management
    branch: master
  when: manual